// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const pages: { "home": { "hero": { "brandAlt": string; "button": string; "eyebrow": string; "status": string; "subtitle": string; "title": string } } };
  export const home: { "hero": { "brandAlt": string; "button": string; "eyebrow": string; "status": string; "subtitle": string; "title": string } };
}
